global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['chat-service:8082']

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:8083']
