server:
  port: 8083

spring:
  application:
    name: chat-service
  ai:
    openai:
      api-key: OPENAI_API_KEY
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: chat-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
